packages:
  - apps/*
  - packages/*

catalog:
  '@radix-ui/colors': ^3.0.0
  '@vanilla-extract/css': ^1.17.4
  solid-js: ^1.9.10
  typescript: ^5.9.3

onlyBuiltDependencies:
  - esbuild
  - svelte-preprocess
